name = "notlify_2"
compatibility_date = "2024-08-20"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiY2ZlNTYwMzktMzFiYy00MjM5LWI3NTEtYzRjOWE1NDY1NTU0IiwidGVuYW50X2lkIjoiZGMwMDc3ZTlkODU1NTVlMGE2OTMxMGU4N2Y1ZWE0NGEyMTBkMzc1NDhhNGIxNWViY2MxMDllMzRiYTE1NTljYyIsImludGVybmFsX3NlY3JldCI6IjI5NDMxMWRkLTg0NzAtNDZmOS1iNmU4LWQ0YTU1ZDBjYzMwZiJ9.wkuUOi5XDbIR2aAp9eqJGRP56nvhQxsQ3FW_SbpSLvU"

